dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install flake8
- pip install coveralls
script:
- flake8 .
- python setup.py test
after_success:
- coveralls
before_deploy:
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: __token__
  password:
    secure: LDSy0dXqqvNeAyoT/MvNfbRn+4JmP3N22ZlVjt2Uh2CcLVNUZAKolnmpNzl93Dkmi4i9WEW4W8RELm1KNlayZGEdG+H0SP1fxj6lWH9PCadTwJg1AhBZ/7NqYumWyH7g+Hw+b7IycNBvmgW/VKyBD9otw8PzcLYir9NdvmUVge2o/TCsguVglW3Boe9OUdLLp/SqCxqG38IRHIyGAi3/w1C4QMwlf1dyqmNQvh47mgMoY4q+tSFoFpQZYNHuG8OkQMpl7ooNw3E8LM2Q1x/2dVMq5auUzWoEt6zY0fAl/9TQtKDrC4ZA6QL4iR5bHOTr5fDXNurYKbUJ2RqMDyAs1+lrZF1C/tbhFUfdCRBDsJysCj/kFsekMAztBfoxhhy1IywPpMzz3PmoY+/LNkXp7Pos5J8k3PDbStbpGYnm7r0O/3LJg25bMZS6vIlPXImCSSXOlR9NBKicESu29qBucK0XQfJ5NsSXGm6am1G7QB4HNs/su7opiTzolbnb9zx0FMbYqoICmWnozt5pjaWTB05bpBX8EAsr/WQHlu3XELQuk/PvtpyZ+m1G0iXiT8DuVLz1CnDrNkW0XE5s/Asd2zyK07yKGIHKwwbDAnhqMKfHCDqlAz/sKj/NwgQ/b+j9RvL6dj32MYzGCNDJFsMpSCRpLccBKWwOG1hn8kz8Hdo=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
