dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install flake8
- pip install coveralls
script:
- flake8 .
- python setup.py test
after_success:
- coveralls
before_deploy:
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: adalekin
  password:
    secure: GxJu9vZjZPwEaozeEsSYao6kNMg5yiOdc8rLBvc8YRdw0gsvP+7sRmf0qCzqzGHqa8HYHmwJwlGL8EjTKOfsjvLRd3Dx9ThvYZuK5w3I7tIPXgwWxDYSCQvjTQIgTd1msVr9+trlSUBbDz7R7hwkZDmDHM0kva4YJA/c+ys7nQQA5xvdLp+GY+Vn2LxCfTbm1A8bLKtdSkV85XB6ehhAxA2wptShz9qSAVKmmAHn23pJIvCb8ps5xodZtQD29Awtl1PVPCehOJAjkIB70uPTl2Q/LF6wl5iqB0oLofqguWSaHON9QMZ8ksi/UCBEQ6yEEyqMQAHyquehw6+iTlV+XjRXRdm+t8CCNKP25uW2HJEnFdOp7yqmIxB/jtqBi9hEVNLRMe4qJQSBzTKGibpVmiYLsGAqdAXw5Ilw/9tJNOaS86X0MdWDvtCi8fP+l9tbs8b8tkJz27i2kuRLMnO8aqIEIqjoXLTAtVB0/afBV+UVnKdnav7MEatJh5UmoU//UEWl5tUUz/lTWH7F2ud3v0HzS9wy6nau/dIZyvu4LXb8Q8t3N2kBUIqcybY7US6eBsv67bukVCGjS9NnkIqMKOmlFNC5Rm8hOSjwnuJvMOqLFGDi9NhT/stBtDX24tmrqNbiOJciEhW3xjEz0lL9wYNohxGkWIRDudIn2C+i9O0=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
