dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install flake8
- pip install coveralls
script:
- flake8 .
- python setup.py test
after_success:
- coveralls
before_deploy:
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: __token__
  password:
    secure: wU+11Le8Zrj64VdIJCBe20aC195p4xDFGd99jXrDNJ+9mQbI/4CKbiLkPpKjgNiRWKWXTtkhZARf5BpE7R8F8xk61FaJ3YA1y6aLFzZPVWWQV3UtifNU/YZRFPNW4gNkOFyzq+TyC+oLys4FSn/AuZ55VGegT3qMEc6NqE+XfyIjLdbvqrDlHZGPhp901x/FErUQV/5iRqvnFPsaV7dEORhZSODZfP9pg3aFfHH/LMF9afynUsT2mMZ+eHdaQ6Rq5zTC6uvNncfQ0cPOVbrhkPjdFEzZLGYU+ShYqDUCXILoRd88fh9RDhiOefOkl0bY+IrVmWituuNIhmTpgjxELKKdRVB+7PPm6rD3aqGA+EGpfMpACUaP0IOIbW59MS7ULknXRhYbUGFCyrmS79fE9iddayCbEgTeleXaM3ucxRRV3f0gtUKAJzVQcdCJa6jXsaVTiBDYKPiDFuu9kDC0SEIoYCp29o/EEwr4Jb5TvCrD+0sSwP0iAyhzdGO423zwf8BRZLAre7xIHIUeh1JYXd4oYpMB6cXwdXd98wGnTucAwZ2dZh/qszzLxiZA65+159sG4CMqqvxEsGGy28nhW4HQ41wDLAYxDkIFQOqM8LJm2PNHO4Vq+qk6euVX3hWsYNfHzZJKLGevsWkBFAUKPntrTDn9z7xkJ4e4nt5x8Hw=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
