language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
script:
- flake8 .
- pytest
deploy:
  provider: pypi
  user: adalekin
  password:
    secure: eERiT9kvEEK2OK6FuPzl1hXOvaZubvBohx5nawb7lbggqDNKRcJaQ2JAGop2orWkLQKXzuONWXQA64EbVLQgIqwzdfT6/82PEwOAIgXpjw7YrTNEWXeYEbaz3OhSdTCTWtdMlm/GNKc0hJIJsenQpsmSn6GxBwIbrMhpfftK2ifXMZYwWlmZK149E+al/YtLPEf3+BkQzHErbJVRTqjQHSzLB9pOBVYxctTNxhjd61nazcIaLWUoYrjfbb3AJ/V6WFMb5eZKNIncuFM+2rxFXivk8HA3RT3pKPcXY9ZWzowegMS/38XpWK2tnrO91y1Xc+qc/apJPjdxCOq0o+OOgoMJAOgPbNvvRZeb/jLc5KNN3kh+SDYe3G6ExIACJBYe1R1H8fhC/xF2bZ6LhoNHSe+SDqs4qxHS/yLiH8S4PIT0LxVpyfgg9bf7S6+AjIAmq/AQCcQzEZwJAR1bwWcrLedlYTqMGIqyIInIds0lJKl74FFCXq5MDmeT9PdSg+gV0HTozihF3rjQUGvy6dwOHeoDLZfhK+YciZORpqkWLREubHFhs68vD0pNJymovIYY3HCP0ArtvR7MSByhrXj/tMMsUmx/wZRs9vOEb9354GhLWhQQqb5T4F2foxSBjgnbNDQJGTzbGshxsS+fnAsgmFy0TNsLDmdMYsGJRlawRic=
  on:
    branch: master
    repo: adalekin/connexion-buzz
