language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
script:
- flake8 .
- pytest
deploy:
  provider: pypi
  user: adalekin
  password:
    secure: OlPxJtyfQalPjV8AbylFM/oKYjfEAUHsoWdyWNd8DI75xA7MRJXWq7ifPKx573okPBEJfe9XyXxBMPllawJXoy4DdE/h69eBRC4wnTnTPe0Rg+HMKFU+bkSGhwdyHlDgnxgl+9XUPTFtj/dklCdkTxr00MsBYn7oQ9uY3HAJwtbQvwSsMhqSjvqklZLg1rF+y4E4ZlR8JB9ujsBYjmu3j84rzO0gYs+AQRTAfonCyRF9HEJgE3scHokdzbC5YDEpq2yC7+ZphrbM7jO2DBgyK/mXEJVI1LBCG98VfkkIwMeDWaKveiQQ74gVG4Hpi69RN0AdDzO2QJ3uhs7QCT9THSi7EBdNOSLjPDi2jkkwIoUgPVgMmjYAQ7QdeCY3XlV2WEz8UAmfLon7U29ztiKl8HSvFRLQkhBdH9qQP5m64utnNNN+ylZ1Rg+1kW0N29Yuur++3GdGMOcFx9DxQ8Ht6ZWF1imKfg+JRW9k4xecakcxzgkDprWrOpOVsvGS8dTqhp0olOJmg7fCjqKCgyBc7ZWm3qrtbV/GfWw2Ix9WVPLWw0Zpi4Oyz57jnUR+NGT2FyWh2zz9B7UFJUQlr51c2VrxB6nz45OSE9fwGt4m7bMNcmhG24Rg/b7gKzYniQJrGI1lSMuR7BgixN+goBbtQuOqEdSFxng7NkUfCkM1xiA=
  on:
    branch: master
