dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install flake8
- pip install coveralls
script:
- flake8 .
- python setup.py test
after_success:
- coveralls
before_deploy:
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: __token__
  password:
    secure: wDlZU59RRSfJo8mx49ZwqTMeIVAU1ipKUdsry8GBvJAmKzI9ukfeFAa3FUzMP322OsLI1MWYsn14jVWMliTHJy2mKLhdr+NcZut+BXrVOmtrvBoFbOTYqJjAp2r/pGBZQlnphPaFCEEbUcX/YpQXOuKN7s3loMKtDzPp3oNghOYO6JzTPVwFWBmpGIFFe1KfVMT7ZFgzBjTTykWubjfAMQQ/7AJUziDO3FIxwTEn5hdUGwBWNz8XSnIqQ1/uvRAVCDyIHaqY+MnUJLTgLk3oB9EW29h0eTygsn6Na3k6zWyYGK5JirPBObZiOLSW11xsRoAx46BryinvXKGhcL3JzCbXyfjMS6YeIvZkn2sHezkCAlEBAymw5cGkWJ64W2mtysQFZTp1Gr1rWKgx1zlfuMUFyicyOPr4cCNv/Nj6bvUdsorx8yJXukf1kF5F8a6bmW2J8HTgzEoKY1JahskqiBAY8bv/z0L6TFc/OCVHyJf0OI2YefSj1GRjHq250k9KW6gN+1o3XQQILK2J+q+1AFQwauJwAFN89VNLhQHGfQoIDRfvShbFfqkArWP410AOHswA/b8Ygk1jA+tirh6Eq3fLVOUGVo0vPI3PjoFV2y00vJ9uUkUflaXtaqxTIf15IbUrf6ZNkyW5p6kUdLZwctHrg1WRGGjanuLwIG47WFc=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
