dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install flake8
- pip install coveralls
script:
- flake8 .
- python setup.py test
after_success:
- coveralls
before_deploy:
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: adalekin
  password:
    secure: RY8wPASFmw7p8ILmnuG5ZKlp6NDDX+mnuZYjiprSR58CX61NSPogMKQTsn+eTXAFvQGDCTLXGZD8R4vmgaCKHYkvqF04SMqHCMmXl5Q6KaSWRhIma46c4rpVXLpzPlHxuHo/CAL78mqBpiMBRG8dtIREe0LSAZKXJJHQ5tZt26c3Dz/+MpqY1LwYlehBScjY2/+ovvnfjWM7A6uHysGPqk71VacgrwkH4i4xQNQ90OC0zVZ9kceYWYS46ILOUrabYdFXZa0sWDlY+tobZOXJiW0Q5NyGaf6YWKLeTjxFlZLpDmIE4kAilLsyRhiDt/+X67WFWVIR1ZtVroLvzFPVpL3Su4oT6ebAKUTAVkJZxWNOU8b2BQ1YBL7KGt+tAtw2f3j/eaTljbXesHtjAIdXHjIwT/Ke+2bNro1Xv+H4mv5ioy/vOEbeyDHrv8HfVZwts0hrPxDzYjvsyDRRy+RlOsLtdqmd7hHjVc+gnUcVmN9JpK40wUzYHTkW8jh5O234l/rOHnE/Pa7ifadWqMOvL9IbxFZBbB9DOX5ZFLOpYBRKHwNx1NqP+DrMtw66ad59B4WxJfakzMDmizR/R3DX/hMcMguE/ii3JKMGRx3Wthxqy5Ml5hhIu2qphBIurI3M7QS9Y3fgGuLCm/4ZvPCzfD/VXt5C5FR48ozfrl1Hefk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
