dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install flake8
- pip install coveralls
script:
- flake8 .
- python setup.py test
after_success:
- coveralls
before_deploy:
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: __token__
  password:
    secure: FbJ5AUSOBI9s4rtqSEtK5ILTCkjWeSevIL/EP0hHKMjOzXw6W20VCgPndmacUjBgtHvhU3XEO0ViRLHfh6O6O0CQzHCZWTGFrgG2Uh3AkV1JUD7kXTJ4fmP+vnKAq3X1T5yQwbSQRzoNWshkMaPojlO+WntSMjRTRc3s3PJSGijCgJhpJSXK8sEIS4pA8X3u3ALGIt46xXp6wyQYVzSXvjVHtp7WeOUFQKEX0zYZm8NkWkn6SrDNMnJH9JHZiw/BlDy7YOVmxfNrItfHgPqx32JCREwzFepDUa6/phUwzmZasKU0mTaJ9UqsX4LwYB4JoU9xFDemIgXccfoN70PSQbgrSMc90tElbngrgNC41jlugB5TdqHNLaFi59+XB74sClDOjN7qLw/NzkDgpthqouljYzhUO/xHrFrGizJcVOvVC4hwj4m32hmlIvr87HWvxiXcAQHW4sMxHHQFh8T91KFf4iiFx3HW3dHc4zf+osUa5I+Q709w3PaGE661PfpxLJSY1CybxkNa2nFZ0wblGAKrUF5MeN263OjPl0iFv92QKKEmQSHaNhgA4/OJMMPU9+eW3Hl5v27D3pUA7Y5WGOA7fQ9VcZalGCOuMjmDM0hTUcM/w/p53gRNBVw9Kc0F2tMDOp/nTzzE5eEzgxHVGmXir0hiR+9CJPNY9bgnaNM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
