language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements-dev.txt
script:
- flake8 .
- pytest
deploy:
  provider: pypi
  user: adalekin
  password:
    secure: I/+Mqh7OTCHHJfXi8ENpoY23wPI7ntzbkmSG3SJm0+EJ3KcmlPDZn0MrtFBQD+5/sr3vYsZ3gXH6IENxBvVrr8SRj1yvpngdoCgdYwxJppcmFfsOR+lLYzvlPEC5O/eFYYP+w6UOoLsQp9SIrH7WIAizt3JHkq+sfT4q4/NrQD+4lymEQl9/gs2woInSTckpNeK4gMS+hVm3/GD4ZEl/d26AyWksHt0ev11fj2EHxuZ/+NHexBVGIoIZXoyGiXAV0lqP35GN3apdLvvB/xBX37tJVe98KHFqOtV7IAjXD6rqxXgMHLLKqay2SzJvQLz+aL5QLdHZEl09RHqYve/AfugeMKHE0rcOQDIEemUQNB8x611tPmUTkreaM2VIRGKCWmUU/Xwp07oGcl478IKAJq327CQOWMAIWZA65py5fDqalNxg43IR66NENnOsVmvF9zLwIr+oaJTGSL1rckAdP91wEriXmfQWxc4RYr5HUiEuxmSDJdR845qSo4nVSeolW6RMXa84f+COYitLaTu/7sn7HdJITgBHVOenuasoZDTiAdyz8n3+QUKv5dhDVfoSsXQKF0bR54+5ZKKpfHk+o8+d2YzN7uZFfS3FMGPNu4jJe1azYeKyou1fmjiGAR+b/yZOh7mLaxG9w63wwzMn+/TAss0M58F7ACIcskS+whc=
  on:
    branch: master
